{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wikimo
  labels:
    {{- include "wikimo.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "wikimo.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
{{- end }}
